openapi: 3.0.0
info:
    version: 1.0.0
    title: Monki Map Placemarks API
servers:
    - url: https://api.monkiprojects.com/v1
      description: Monki Projects API v1 (prod)
    - url: https://pre-prod.api.monkiprojects.com/v1
      description: Monki Projects API v1 (pre-prod)
paths:
    '/placemarks':
        post:
            summary: Create Placemark
            description: Creates a placemark.
            operationId: createPlacemark
            tags:
                - placemarks
                - localized
            parameters:
                - $ref: '#/components/parameters/Locale'
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreatePlacemark'
            responses:
                201:
                    description: Successfully Created
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PlacemarkFullDetails'
                400:
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                            examples:
                                'Invalid coordinates':
                                    $ref: '#/components/examples/InvalidCoordinatesError'
                                'Invalid type':
                                    $ref: '#/components/examples/InvalidTypeError'
                                'Placemark type not found':
                                    $ref: '#/components/examples/PlacemarkTypeNotFoundError'
                                'Invalid feature':
                                    $ref: '#/components/examples/InvalidFeatureError'
                                'Invalid technique':
                                    $ref: '#/components/examples/InvalidTechniqueError'
                                'Invalid benefit':
                                    $ref: '#/components/examples/InvalidBenefitError'
                                'Invalid hazard':
                                    $ref: '#/components/examples/InvalidHazardError'
                401:
                    $ref: '#/components/responses/UnauthorizedError'
        get:
            summary: List Placemarks
            description: Lists all published placemarks by default. If a `state` query parameter is set, this endpoint will list all placemarks in the specified state.
            operationId: listPlacemarks
            tags:
                - placemarks
                - localized
            parameters:
                - $ref: '#/components/parameters/PlacemarkState'
                - $ref: '#/components/parameters/Locale'
            responses:
                200:
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ArrayOfPlacemarks'
                400:
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                            examples:
                                'Invalid state query param':
                                    $ref: '#/components/examples/InvalidStateQueryParamError'
    '/placemarks/{placemarkId}':
        get:
            summary: Get Placemark
            description: Gets a placemark's details.
            operationId: getPlacemark
            tags:
                - placemarks
                - localized
            parameters:
                - $ref: '#/components/parameters/PlacemarkId'
                - $ref: '#/components/parameters/Locale'
            responses:
                200:
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ArrayOfPlacemarks'
                404:
                    $ref: '#/components/responses/PlacemarkNotFoundError'
        delete:
            summary: Delete Placemark
            description: Deletes a placemark.
            operationId: deletePlacemark
            tags:
                - placemarks
            parameters:
                - $ref: '#/components/parameters/PlacemarkId'
            responses:
                204:
                    description: Successfully Deleted
                403:
                    description: Forbidden
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                            examples:
                                'Not your placemark':
                                    $ref: '#/components/examples/CannotDeleteSomeoneElsesPlacemarkError'
                404:
                    $ref: '#/components/responses/PlacemarkNotFoundError'
    '/placemarks/{placemarkId}/submit':
        get:
            summary: Submit Placemark
            description: Submits a placemark.
            operationId: submitPlacemark
            tags:
                - placemarks
                - placemark-submission
            parameters:
                - $ref: '#/components/parameters/PlacemarkId'
            responses:
                200:
                    description: Successfully Submitted
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PlacemarkSubmissionReport'
                403:
                    description: Forbidden
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                            examples:
                                'Not your placemark':
                                    $ref: '#/components/examples/CannotSubmitSomeoneElsesPlacemarkError'
                                'Already submitted':
                                    $ref: '#/components/examples/CannotSubmitPlacemarkTwiceError'
                404:
                    $ref: '#/components/responses/PlacemarkNotFoundError'
    '/placemarks/{placemarkId}/submission':
        get:
            summary: Get Placemark Submission Report
            description: Get a placemark's submission report.
            operationId: getPlacemarkSubmissionReport
            tags:
                - placemarks
                - placemark-submission
            parameters:
                - $ref: '#/components/parameters/PlacemarkId'
            responses:
                200:
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PlacemarkSubmissionReport'
                404:
                    $ref: '#/components/responses/NoPlacemarkSubmissionFoundError'
    '/placemarks/{placemarkId}/submission/reviews':
        post:
            summary: Add Placemark Submission Review
            description: Adds a submission review to a placemark.
            operationId: addPlacemarkSubmissionReview
            tags:
                - placemarks
                - placemark-submission
            parameters:
                - $ref: '#/components/parameters/PlacemarkId'
            requestBody:
                content:
                  application/json:
                    schema:
                        $ref: '#/components/schemas/CreatePlacemarkSubmissionReview'
            responses:
                200:
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PlacemarkSubmissionReview'
                400:
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                401:
                    $ref: '#/components/responses/UnauthorizedError'
                403:
                    $ref: '#/components/responses/ForbiddenModeratedFlagError'
                404:
                    $ref: '#/components/responses/NoPlacemarkSubmissionFoundError'
        get:
            summary: List Placemark Submission Reviews
            description: Lists a placemark's submission reviews.
            operationId: listPlacemarkSubmissionReviews
            tags:
                - placemarks
                - placemark-submission
            parameters:
                - $ref: '#/components/parameters/PlacemarkId'
            responses:
                200:
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ArrayOfPlacemarkSubmissionReviews'
                401:
                    $ref: '#/components/responses/UnauthorizedError'
                404:
                    $ref: '#/components/responses/NoPlacemarkSubmissionFoundError'
    '/placemarks/features':
        get:
            summary: List Placemark Features
            description: Lists placemark features.
            operationId: listPlacemarkFeatures
            tags:
                - placemarks
                - localized
            parameters:
                - $ref: '#/components/parameters/Locale'
            responses:
                200:
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ArrayOfPlacemarkFeatures'
    '/placemarks/techniques':
        get:
            summary: List Placemark Techniques
            description: Lists techniques available for placemarks.
            operationId: listPlacemarkTechniques
            tags:
                - placemarks
                - localized
            parameters:
                - $ref: '#/components/parameters/Locale'
            responses:
                200:
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ArrayOfPlacemarkTechniques'
    '/placemarks/benefits':
        get:
            summary: List Placemark Benefits
            description: Lists placemark benefits.
            operationId: listPlacemarkBenefits
            tags:
                - placemarks
                - localized
            parameters:
                - $ref: '#/components/parameters/Locale'
            responses:
                200:
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ArrayOfPlacemarkBenefits'
    '/placemarks/hazards':
        get:
            summary: List Placemark Hazards
            description: Lists placemark hazards.
            operationId: listPlacemarkHazards
            tags:
                - placemarks
                - localized
            parameters:
                - $ref: '#/components/parameters/Locale'
            responses:
                200:
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ArrayOfPlacemarkHazards'
components:
    parameters:
        PlacemarkId:
            in: path
            name: placemarkId
            description: A placemark `ID`.
            required: true
            schema:
                $ref: '#/components/schemas/ID'
        PlacemarkState:
            in: query
            name: state
            description: A state to filter placemarks.
            schema:
                $ref: '#/components/schemas/PlacemarkState'
        Locale:
            in: query
            name: locale
            description: The desired locale for response localization.
            schema:
                $ref: '#/components/schemas/Locale'
    schemas:
        # === Molecules ===
        CreatePlacemark:
            description: An object with data required to create a new placemark.
            type: object
            required:
                - name
                - latitude
                - longitude
                - type
            properties:
                name:
                    $ref: '#/components/schemas/PlacemarkName'
                latitude:
                    $ref: '#/components/schemas/Latitude'
                longitude:
                    $ref: '#/components/schemas/Longitude'
                type:
                    $ref: '#/components/schemas/PlacemarkTypeId'
                caption:
                    $ref: '#/components/schemas/PlacemarkCaption'
                images:
                    $ref: '#/components/schemas/ArrayOfImages'
                features:
                    $ref: '#/components/schemas/ArrayOfPlacemarkFeatureIds'
                goodForTraining:
                    $ref: '#/components/schemas/ArrayOfPlacemarkTechniqueIds'
                benefits:
                    $ref: '#/components/schemas/ArrayOfPlacemarkBenefitIds'
                hazards:
                    $ref: '#/components/schemas/ArrayOfPlacemarkHazardIds'
        PlacemarkFullDetails:
            description: A placemark, with all its details.
            type: object
            required:
                - id
                - name
                - latitude
                - longitude
                - type
                - category
                - state
                - caption
                - satelliteImage
                - images
                - city
                - country
                - features
                - goodForTraining
                - benefits
                - hazards
                - url
                - htmlUrl
                - createdAt
                - updatedAt
            properties:
                id:
                    $ref: '#/components/schemas/ID'
                name:
                    $ref: '#/components/schemas/PlacemarkName'
                latitude:
                    $ref: '#/components/schemas/Latitude'
                longitude:
                    $ref: '#/components/schemas/Longitude'
                type:
                    $ref: '#/components/schemas/PlacemarkType'
                category:
                    $ref: '#/components/schemas/PlacemarkCategory'
                state:
                    $ref: '#/components/schemas/PlacemarkState'
                caption:
                    $ref: '#/components/schemas/PlacemarkCaption'
                satelliteImage:
                    $ref: '#/components/schemas/Image'
                images:
                    $ref: '#/components/schemas/ArrayOfImages'
                city:
                    $ref: '#/components/schemas/PlacemarkCity'
                country:
                    $ref: '#/components/schemas/PlacemarkCountry'
                features:
                    $ref: '#/components/schemas/ArrayOfPlacemarkFeatures'
                goodForTraining:
                    $ref: '#/components/schemas/ArrayOfPlacemarkTechniques'
                benefits:
                    $ref: '#/components/schemas/ArrayOfPlacemarkBenefits'
                hazards:
                    $ref: '#/components/schemas/ArrayOfPlacemarkHazards'
                url:
                    $ref: '#/components/schemas/URL'
                htmlUrl:
                    $ref: '#/components/schemas/URL'
                createdAt:
                    $ref: '#/components/schemas/DateTime'
                updatedAt:
                    $ref: '#/components/schemas/DateTime'
        Placemark:
            description: A placemark, with minimum data for rendering on a map.
            type: object
            required:
                - id
                - name
                - latitude
                - longitude
                - type
                - category
                - state
                - url
                - htmlUrl
                - createdAt
                - updatedAt
            properties:
                id:
                    $ref: '#/components/schemas/ID'
                name:
                    $ref: '#/components/schemas/PlacemarkName'
                latitude:
                    $ref: '#/components/schemas/Latitude'
                longitude:
                    $ref: '#/components/schemas/Longitude'
                type:
                    $ref: '#/components/schemas/PlacemarkType'
                category:
                    $ref: '#/components/schemas/PlacemarkCategory'
                state:
                    $ref: '#/components/schemas/PlacemarkState'
                url:
                    $ref: '#/components/schemas/URL'
                htmlUrl:
                    $ref: '#/components/schemas/URL'
                createdAt:
                    $ref: '#/components/schemas/DateTime'
                updatedAt:
                    $ref: '#/components/schemas/DateTime'
            example:
                $ref: '#/components/examples/Spot1'
        ArrayOfPlacemarks:
            description: An array of placemarks.
            type: array
            items:
                $ref: '#/components/schemas/Placemark'
            uniqueItems: true
            example:
                - $ref: '#/components/examples/Spot1'
                - $ref: '#/components/examples/Spot2'
        CreatePlacemarkSubmissionReview:
            description: An object with data required to create a new placemark submission review.
            type: object
            required:
                - opinion
                - comment
            properties:
                opinion:
                    $ref: '#/components/schemas/SubmissionReviewOpinion'
                comment:
                    $ref: '#/components/schemas/ReviewComment'
                issues:
                    $ref: '#/components/schemas/ArrayOfPlacemarkIssues'
                moderated:
                    $ref: '#/components/schemas/ModeratedFlag'
            example:
                $ref: '#/components/examples/CreatePlacemarkSubmissionReview1'
        PlacemarkSubmissionReview:
            description: A placemark submission review.
            type: object
            required:
                - id
                - placemark
                - reviewer
                - opinion
                - comment
                - createdAt
            properties:
                id:
                    $ref: '#/components/schemas/ID'
                placemark:
                    $ref: '#/components/schemas/ID'
                reviewer:
                    $ref: '#/components/schemas/ID'
                opinion:
                    $ref: '#/components/schemas/SubmissionReviewOpinion'
                comment:
                    $ref: '#/components/schemas/ReviewComment'
                issues:
                    $ref: '#/components/schemas/ArrayOfPlacemarkIssues'
                moderated:
                    $ref: '#/components/schemas/ModeratedFlag'
                createdAt:
                    $ref: '#/components/schemas/DateTime'
            example:
                $ref: '#/components/examples/PlacemarkSubmissionReview1'
        ArrayOfPlacemarkSubmissionReviews:
            description: An array of placemark submission reviews.
            type: array
            items:
                $ref: '#/components/schemas/PlacemarkSubmissionReview'
            uniqueItems: true
            example:
                - $ref: '#/components/examples/PlacemarkSubmissionReview1'
                - $ref: '#/components/examples/PlacemarkSubmissionReview2'
        PlacemarkSubmissionReport:
            description: An array of placemark submission reviews.
            type: object
            required:
                - id
                - placemark
                - state
                - reviews
                - createdAt
                - updatedAt
            properties:
                id:
                    $ref: '#/components/schemas/ID'
                placemark:
                    $ref: '#/components/schemas/ID'
                state:
                    $ref: '#/components/schemas/PlacemarkSubmissionState'
                reviews:
                    $ref: '#/components/schemas/ArrayOfPlacemarkSubmissionReviews'
                createdAt:
                    $ref: '#/components/schemas/DateTime'
                updatedAt:
                    $ref: '#/components/schemas/DateTime'
            example:
                $ref: '#/components/examples/PlacemarkSubmissionReport1'
        # === Atoms ===
        # Placemark Data
        PlacemarkName:
            description: A placemark `name`.
            type: string
            minLength: 3
            maxLength: 48
        PlacemarkCaption:
            description: A placemark `caption`. Possibly empty.
            type: string
            nullable: true
        PlacemarkCity:
            description: The city in which a placemark is.
            type: string
            minLength: 1
        PlacemarkCountry:
            description: The country in which a placemark is.
            type: string
            minLength: 1
        PlacemarkState:
            description: A placemark submission state.
            type: string
            enum: [private, submitted, published, rejected]
        # Placemark Types
        PlacemarkType:
            description: A placemark `type`.
            type: object
            required:
                - id
                - title
                - locale
            properties:
                id:
                    $ref: '#/components/schemas/PlacemarkTypeId'
                title:
                    $ref: '#/components/schemas/LocalizedTitle'
                locale:
                    $ref: '#/components/schemas/Locale'
            example:
                id: training_spot
                title: Lieu d'entraînement
                locale: fr-FR
        PlacemarkTypeId:
            description: A placemark type `ID`.
            type: string
            pattern: '^(?:[a-z0-9]+_)*[a-z0-9]+$'
        # Placemark Categories
        PlacemarkCategory:
            description: A placemark `category`.
            type: object
            required:
                - id
                - title
                - locale
            properties:
                id:
                    $ref: '#/components/schemas/PlacemarkCategoryId'
                title:
                    $ref: '#/components/schemas/LocalizedTitle'
                locale:
                    $ref: '#/components/schemas/Locale'
            example:
                id: facility
                title: Salle
                locale: fr-FR
        PlacemarkCategoryId:
            description: A placemark category `ID`.
            type: string
            enum: [spot, facility, misc]
        # Placemark Features
        PlacemarkFeature:
            description: A placemark feature.
            type: object
            required:
                - id
                - title
                - locale
            properties:
                id:
                    $ref: '#/components/schemas/PlacemarkFeatureId'
                title:
                    $ref: '#/components/schemas/LocalizedTitle'
                locale:
                    $ref: '#/components/schemas/Locale'
            example:
                $ref: '#/components/examples/Feature1'
        ArrayOfPlacemarkFeatures:
            description: An array of placemark features.
            type: array
            items:
                $ref: '#/components/schemas/PlacemarkFeature'
            uniqueItems: true
            example:
                - $ref: '#/components/examples/Feature1'
                - $ref: '#/components/examples/Feature2'
        PlacemarkFeatureId:
            description: A placemark feature `ID`.
            type: string
            pattern: '^(?:[a-z0-9]+\+?_)*[a-z0-9]+$'
        ArrayOfPlacemarkFeatureIds:
            description: An array of placemark feature `ID`s.
            type: array
            items:
                $ref: '#/components/schemas/PlacemarkFeatureId'
            uniqueItems: true
            example: [grass, small_wall, stairs]
        # Parkour Techniques
        PlacemarkTechnique:
            description: A technique one can practice on placemarks.
            type: object
            required:
                - id
                - title
                - locale
            properties:
                id:
                    $ref: '#/components/schemas/PlacemarkTechniqueId'
                title:
                    $ref: '#/components/schemas/LocalizedTitle'
                locale:
                    $ref: '#/components/schemas/Locale'
            example:
                $ref: '#/components/examples/Technique1'
        ArrayOfPlacemarkTechniques:
            description: An array of techniques one can practice on placemarks.
            type: array
            items:
                $ref: '#/components/schemas/PlacemarkTechnique'
            uniqueItems: true
            example:
                - $ref: '#/components/examples/Technique1'
                - $ref: '#/components/examples/Technique2'
        PlacemarkTechniqueId:
            description: A technique `ID`.
            type: string
            pattern: '^(?:[a-z0-9]+\+?_)*[a-z0-9]+$'
        ArrayOfPlacemarkTechniqueIds:
            description: An array of technique `ID`s.
            type: array
            items:
                $ref: '#/components/schemas/PlacemarkTechniqueId'
            uniqueItems: true
            example: [double_kong, precision_jump]
        # Placemark Benefits
        PlacemarkBenefit:
            description: A placemark benefit.
            type: object
            required:
                - id
                - title
                - locale
            properties:
                id:
                    $ref: '#/components/schemas/PlacemarkBenefitId'
                title:
                    $ref: '#/components/schemas/LocalizedTitle'
                locale:
                    $ref: '#/components/schemas/Locale'
            example:
                $ref: '#/components/examples/Benefit1'
        ArrayOfPlacemarkBenefits:
            description: An array of placemark benefits.
            type: array
            items:
                $ref: '#/components/schemas/PlacemarkBenefit'
            uniqueItems: true
            example:
                - $ref: '#/components/examples/Benefit1'
                - $ref: '#/components/examples/Benefit2'
        PlacemarkBenefitId:
            description: A placemark benefit `ID`.
            type: string
            pattern: '^(?:[a-z0-9]+\+?_)*[a-z0-9]+$'
        ArrayOfPlacemarkBenefitIds:
            description: An array of placemark benefit `ID`s.
            type: array
            items:
                $ref: '#/components/schemas/PlacemarkBenefitId'
            uniqueItems: true
            example: [covered_area, drinking_fountain]
        # Placemark Hazards
        PlacemarkHazard:
            description: A placemark hazard.
            type: object
            required:
                - id
                - title
                - locale
            properties:
                id:
                    $ref: '#/components/schemas/PlacemarkHazardId'
                title:
                    $ref: '#/components/schemas/LocalizedTitle'
                locale:
                    $ref: '#/components/schemas/Locale'
            example:
                $ref: '#/components/examples/Hazard1'
        ArrayOfPlacemarkHazards:
            description: An array of placemark hazards.
            type: array
            items:
                $ref: '#/components/schemas/PlacemarkHazard'
            uniqueItems: true
            example:
                - $ref: '#/components/examples/Hazard1'
                - $ref: '#/components/examples/Hazard2'
        PlacemarkHazardId:
            description: A placemark hazard `ID`.
            type: string
            pattern: '^(?:[a-z0-9]+\+?_)*[a-z0-9]+$'
        ArrayOfPlacemarkHazardIds:
            description: An array of placemark hazard `ID`s.
            type: array
            items:
                $ref: '#/components/schemas/PlacemarkHazardId'
            uniqueItems: true
            example: [security, security_cam, slippery_surface]
        # Placemark Issues
        PlacemarkIssue:
            description: A placemark issue.
            type: object
            required:
                - id
                - placemark
                - issuer
                - reason
                - comment
                - state
                - createdAt
            properties:
                id:
                    $ref: '#/components/schemas/ID'
                placemark:
                    $ref: '#/components/schemas/ID'
                issuer:
                    $ref: '#/components/schemas/ID'
                reason:
                    $ref: '#/components/schemas/PlacemarkIssueReason'
                comment:
                    $ref: '#/components/schemas/PlacemarkIssueComment'
                state:
                    $ref: '#/components/schemas/PlacemarkIssueState'
                createdAt:
                    $ref: '#/components/schemas/DateTime'
            example:
                $ref: '#/components/examples/PlacemarkIssue1'
        PlacemarkIssueComment:
            description: A comment in a placemark issue.
            type: string
            minLength: 4
            example: There is no tree on this spot!
        PlacemarkIssueReason:
            description: The reason of a placemark issue. For unhandled cases, use `other`.
            type: string
            enum: [name, location, type, caption, satelliteImage, images, address, features, goodForTraining, benefits, hazards, other]
            example: type
        PlacemarkIssueState:
            description: The state of a placemark issue.
            type: string
            enum: [submitted, addressed, denied]
            example: addressed
        ArrayOfPlacemarkIssues:
            description: An array of placemark issues.
            type: array
            items:
                $ref: '#/components/schemas/PlacemarkIssue'
            uniqueItems: true
            example:
                - $ref: '#/components/examples/PlacemarkIssue1'
                - $ref: '#/components/examples/PlacemarkIssue2'
        # Reviews
        ReviewComment:
            description: A review comment. Possibly empty.
            type: string
            example: Great spot, very diverse! I like to go there for long training sessions.
        SubmissionReviewOpinion:
            description: A user's opinion in a submission review. `accepted` and `rejected` are reserved to moderators.
            type: string
            enum: [positive, needs-changes, negative, accepted, rejected]
            example: accepted
        PlacemarkSubmissionState:
            description: The state of a placemark submission.
            type: string
            enum: [submitted, accepted, rejected, moderated]
            example: submitted
        # Coordinates
        Latitude:
            description: The latitude component of a coordinate.
            type: number
            format: double
            minimum: -90
            maximum: 90
        Longitude:
            description: The longitude component of a coordinate.
            type: number
            format: double
            minimum: -180
            maximum: 180
        # Locales
        Locale:
            description: A locale, as described in [Language and Locale IDs](https://tinyurl.com/apple-language-and-locale-ids).
            type: string
            format: locale
            minLength: 2
            default: en
            example: fr-FR
        LocalizedTitle:
            description: A localized `title`.
            type: string
            minLength: 1
        # Other
        ID:
            description: A `UUID` (or `GUID`).
            type: string
            format: uuid
            example: ad959e79-55c3-4445-8c51-a74b6d52691a
        DateTime:
            description: A `Date` with time, as described in [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6).
            type: string
            format: date-time
            example: 2017-07-21T17:32:28Z
        URL:
            description: An `URL`.
            type: string
            format: uri
        Image:
            description: An image `URL`.
            type: string
            format: uri
        ArrayOfImages:
            description: An array of image `URL`s.
            type: array
            items:
                $ref: '#/components/schemas/Image'
            maxItems: 48
            uniqueItems: true
        ModeratedFlag:
            description: A flag saying something has been moderated.
            type: boolean
            example: true
        Error:
            description: An Error.
            type: object
            required:
                - error
                - reason
            properties:
                error:
                    type: boolean
                    example: true
                reason:
                    type: string
    responses:
        # === Errors ===
        # Not Found
        PlacemarkNotFoundError:
            description: Placemark not found
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
                    example:
                        error: true
                        reason: Placemark not found.
        NoPlacemarkSubmissionFoundError:
            description: No placemark submission found
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
                    example:
                        error: true
                        reason: No placemark submission found.
        # Unauthorized
        UnauthorizedError:
            description: Unauthorized
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
                    example:
                        $ref: '#/components/examples/UnauthorizedError'
        # Forbidden
        ForbiddenModeratedFlagError:
            description: Cannot use `moderated` flag.
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
                    example:
                        error: true
                        reason: You need to be a moderator in order to use the `moderated` flag.
    examples:
        # Placemarks
        Spot1:
            summary: Example spot
            value:
                id: 4f9058b3-3f8f-4b10-b3c0-e28c654012e4
                name: Espace de street workout Vincent Gâche
                latitude: 47.207423
                longitude: -1.547817
                type:
                    id: calisthenics_park
                    title: Parc de street workout
                    locale: fr-FR
                category:
                    id: spot
                    title: Spot
                    locale: fr-FR
                state: published
                url: https://api.monkiprojects.com/v1/placemarks/4f9058b3-3f8f-4b10-b3c0-e28c654012e4
                htmlUrl: https://monkiprojects.com/placemarks/4f9058b3-3f8f-4b10-b3c0-e28c654012e4
                createdAt: 2020-12-02T01:43:52.285Z
                updatedAt: 2020-12-22T22:26:11.618Z
        Spot2:
            summary: Example spot
            value:
                id: 31256d06-7786-4555-8592-ec20e9c9cdfb
                name: Porte des deux moulins
                latitude: 46.155295
                longitude: -1.159034
                type:
                    id: training_spot
                    title: Lieu d'entraînement
                    locale: fr-FR
                category:
                    id: spot
                    title: Spot
                    locale: fr-FR
                state: published
                url: https://api.monkiprojects.com/v1/placemarks/31256d06-7786-4555-8592-ec20e9c9cdfb
                htmlUrl: https://monkiprojects.com/placemarks/31256d06-7786-4555-8592-ec20e9c9cdfb
                createdAt: 2020-04-15T15:28:41.729Z
                updatedAt: 2020-04-15T15:28:41.729Z
        # Placemark Features
        Feature1:
            summary: Example placemark feature
            value:
                id: grass
                title: Herbe
                locale: fr-FR
        Feature2:
            summary: Example placemark feature
            value:
                id: small_wall
                title: Petit mur
                locale: fr-FR
        # Parkour Techniques
        Technique1:
            summary: Example technique
            value:
                id: double_kong
                title: Double saut de chat
                locale: fr-FR
        Technique2:
            summary: Example technique
            value:
                id: precision_jump
                title: Saut de précision
                locale: fr-FR
        # Placemark Benefits
        Benefit1:
            summary: Example placemark benefit
            value:
                id: covered_area
                title: Espace couvert
                locale: fr-FR
        Benefit2:
            summary: Example placemark benefit
            value:
                id: drinking_fountain
                title: Fontaine à eau
                locale: fr-FR
        # Placemark Hazards
        Hazard1:
            summary: Example placemark hazard
            value:
                id: security
                title: Sécurité
                locale: fr-FR
        Hazard2:
            summary: Example placemark hazard
            value:
                id: security_cam
                title: Caméra de sécurité
                locale: fr-FR
        # Placemark Submission Reviews
        CreatePlacemarkSubmissionReview1:
            summary: Example placemark submission review creation
            value:
                opinion: positive
                comment: Everything looks good.
        PlacemarkSubmissionReview1:
            summary: Example placemark submission review
            value:
                id: 5881cf6b-1d3a-48d2-a84c-9a625adbea20
                placemark: f6236b3a-65f1-4157-84f7-f22d6cff8a0a
                reviewer: e8636f06-5a1c-45a2-b1e9-5a693c98c9c8
                opinion: positive
                comment: ''
                createdAt: 2020-09-23T07:46:57.524Z
        PlacemarkSubmissionReview2:
            summary: Example placemark submission review
            value:
                id: b1e642f9-f0cd-4169-bd3f-2441f37b2b88
                placemark: 2f5bdf5a-8695-4ace-8def-41ba9f632a97
                reviewer: 0350cf76-44ab-480c-8e62-77b47b386827
                opinion: negative
                comment: I know this place, there's no spot here! This should not be accepted.
                issues:
                    - $ref: '#/components/examples/PlacemarkLocationIssue'
                createdAt: 2020-10-05T09:23:21.836Z
        PlacemarkSubmissionReport1:
            summary: Example placemark submission report
            value:
                id: 24ffb61e-ad56-4244-bbd5-673944e74116
                placemark: 6af987db-b1f9-4f9d-ab2e-c330b4ec78bd
                reviews:
                    - $ref: '#/components/examples/PlacemarkSubmissionReview1'
                    - $ref: '#/components/examples/PlacemarkSubmissionReview2'
                createdAt: 2020-09-23T07:46:57.524Z
                updatedAt: 2020-10-05T09:23:21.836Z
        # Placemark Issues
        PlacemarkIssue1:
            summary: Example placemark issue
            value:
                id: 6037a4cd-0089-4212-a363-98b24d44d1e0
                placemark: faf3c5c7-9d7e-4146-a810-ec3311efe2e9
                issuer: 71b4c5ee-2d39-4262-9785-9352a8723418
                reason: type
                comment: This is not a training spot, it is a parkour facility!
                state: addressed
                createdAt: 2020-08-15T17:01:33.818Z
        PlacemarkIssue2:
            summary: Example placemark issue
            value:
                id: 0d3b0767-611f-4be7-aa93-7f0c7383e0ea
                placemark: a3723353-5e90-4db6-a6af-52ba29407c20
                issuer: 185a29c1-2745-4493-8846-f2c1d776b227
                reason: name
                comment: Everyone refers to this spot as "The maze".
                state: submitted
                createdAt: 2020-12-23T22:52:34.051Z
        PlacemarkLocationIssue:
            summary: Issue about a placemark's location
            value:
                id: eb45729e-e407-4bec-b966-20f752040491
                placemark: 2f5bdf5a-8695-4ace-8def-41ba9f632a97
                reason: location
                comment: I know this place, there's no spot here!
                state: submitted
                createdAt: 2020-07-20T21:16:56.239Z
        # === Errors ===
        # Bad Requests
        InvalidCoordinatesError:
            value:
                error: true
                reason: The provided coordinates are invalid.
        InvalidTypeError:
            value:
                error: true
                reason: The provided placemark type is invalid.
        PlacemarkTypeNotFoundError:
            description: We could not find the placemark type you provided.
            value:
                error: true
                reason: Placemark type not found
        InvalidFeatureError:
            value:
                error: true
                reason: The placemark feature 'lörem/ispUm' is not valid. Query `GET /placemarks/features` for an exhaustive list of available features.
        InvalidTechniqueError:
            value:
                error: true
                reason: The technique 'lörem/ispUm' is not valid. Query `GET /placemarks/techniques` for an exhaustive list of available techniques.
        InvalidBenefitError:
            value:
                error: true
                reason: The placemark benefit 'lörem/ispUm' is not valid. Query `GET /placemarks/benefits` for an exhaustive list of available benefits.
        InvalidHazardError:
            value:
                error: true
                reason: The placemark hazard 'lörem/ispUm' is not valid. Query `GET /placemarks/hazards` for an exhaustive list of available hazards.
        InvalidStateQueryParamError:
            value:
                error: true
                reason: Cannot initialize State from invalid String value lorem_ipsum for key state
        # Unauthorized
        UnauthorizedError:
            description: Authentication information is missing or is invalid.
            value:
                error: true
                reason: Unauthorized
        # Forbidden
        CannotDeleteSomeoneElsesPlacemarkError:
            description: You cannot delete someone else's placemark.
            value:
                error: true
                reason: You cannot delete someone else's placemark!
        CannotSubmitSomeoneElsesPlacemarkError:
            description: You cannot submit someone else's placemark.
            value:
                error: true
                reason: You cannot submit someone else's placemark!
        CannotSubmitPlacemarkTwiceError:
            description: You cannot submit a placemark twice.
            value:
                error: true
                reason: You cannot submit a placemark twice!
tags:
  - name: placemarks
    description: Endpoints related to placemarks.
  - name: localized
    description: Endpoints with localizable responses.
#    externalDocs:
#      url: https://docs.api.monkiprojects.com#localized
  - name: placemark-submission
    description: Endpoints related to placemark submissions.
#    externalDocs:
#      url: https://docs.api.monkiprojects.com#placemark-submission
